(function () {
  const loc = window.ForeignWorkforceMessageLocalization;
  const languages = loc ? loc.languages : [];
  const tones = { formal: '正式清楚', friendly: '親切自然', brief: '簡短直接' };
  const fieldLabels = {
    recipient_zh: '中文姓名', recipient_latin: '護照英文姓名／羅馬拼音姓名', contact_person_zh: '中文聯絡人', contact_person_latin: '聯絡人羅馬拼音姓名', pickup_person_zh: '中文接送人', pickup_person_latin: '接送人羅馬拼音姓名',
    onboard_date: '報到日期', onboard_time: '報到時間', onboard_place: '報到地點', documents: '攜帶文件',
    interview_date: '面試日期', interview_time: '面試時間', interview_place: '面試地點', interview_method: '面試方式',
    medical_date: '體檢日期', meet_time: '集合時間', meet_place: '集合地點', medical_place: '體檢地點',
    document_type: '文件種類', handover_date: '交付日期', handover_method: '交付方式',
    missing_documents: '缺少文件', submit_deadline: '補交期限', submit_method: '提交方式',
    pickup_date: '日期', pickup_time: '時間', flight_or_trip: '班機或車次', pickup_place: '集合地點', contact_method: '聯絡方式'
  };
  const fields = {
    recipient: { kind: 'name', base: 'recipient' }, contact: { kind: 'name', base: 'contact_person' }, pickupPerson: { kind: 'name', base: 'pickup_person' },
    onboardDate: { kind: 'date', id: 'onboard_date' }, onboardTime: { kind: 'time', id: 'onboard_time' }, onboardPlace: { kind: 'place', id: 'onboard_place', default: 'company_first_floor' },
    interviewDate: { kind: 'date', id: 'interview_date' }, interviewTime: { kind: 'time', id: 'interview_time' }, interviewPlace: { kind: 'place', id: 'interview_place', default: 'company_first_floor' }, interviewMethod: { kind: 'option', id: 'interview_method', group: 'methods', options: ['onsite_interview', 'video_call', 'phone_call'], default: 'onsite_interview' },
    medicalDate: { kind: 'date', id: 'medical_date' }, meetTime: { kind: 'time', id: 'meet_time' }, meetPlace: { kind: 'place', id: 'meet_place', default: 'company_first_floor' }, medicalPlace: { kind: 'place', id: 'medical_place', default: 'hospital_entrance' },
    documentType: { kind: 'option', id: 'document_type', group: 'documents', options: ['passport', 'arc'], default: 'passport' }, documents: { kind: 'multiOption', id: 'documents', group: 'documents', options: ['passport', 'arc', 'health_card', 'work_permit', 'bank_book', 'photo', 'medical_report'], default: ['passport', 'arc'] },
    handoverDate: { kind: 'date', id: 'handover_date' }, handoverMethod: { kind: 'option', id: 'handover_method', group: 'methods', options: ['in_person', 'give_to_contact', 'send_line', 'send_email'], default: 'in_person' },
    missingDocuments: { kind: 'multiOption', id: 'missing_documents', group: 'documents', options: ['passport', 'arc', 'health_card', 'work_permit', 'bank_book', 'photo', 'medical_report'], default: ['passport', 'arc'] }, submitDeadline: { kind: 'date', id: 'submit_deadline' }, submitMethod: { kind: 'option', id: 'submit_method', group: 'methods', options: ['in_person', 'give_to_contact', 'upload_photo', 'send_line', 'send_email', 'company_system'], default: 'in_person' },
    pickupDate: { kind: 'date', id: 'pickup_date' }, pickupTime: { kind: 'time', id: 'pickup_time' }, flight: { kind: 'text', id: 'flight_or_trip', default: 'CI753' }, pickupPlace: { kind: 'place', id: 'pickup_place', default: 'airport_arrival_hall' }, contactMethod: { kind: 'text', id: 'contact_method', default: '0912-345-678' }
  };
  const scenarios = [
    { id: 'onboarding', name: '報到通知', purpose: '通知報到日期、時間、地點與需攜帶文件。', tones: ['formal', 'friendly', 'brief'], fields: [fields.recipient, fields.onboardDate, fields.onboardTime, fields.onboardPlace, fields.documents, fields.contact], optional_phrases: ['arrive_early', 'bring_original', 'reply_confirm'] },
    { id: 'interview', name: '面試安排', purpose: '安排面試資訊，確認面試方式、地點與攜帶文件。', tones: ['formal', 'friendly', 'brief'], fields: [fields.recipient, fields.interviewDate, fields.interviewTime, fields.interviewPlace, fields.interviewMethod, fields.documents, fields.contact], optional_phrases: ['arrive_early', 'reply_confirm'] },
    { id: 'medical', name: '體檢提醒', purpose: '提醒體檢日期、集合時間、集合地點與體檢地點。', tones: ['formal', 'friendly'], fields: [fields.recipient, fields.medicalDate, fields.meetTime, fields.meetPlace, fields.medicalPlace], optional_phrases: ['no_breakfast', 'bring_health_card', 'be_on_time', 'tell_medicine'] },
    { id: 'passport_arc', name: '收取護照或居留證', purpose: '通知護照或居留證等文件交付與收取安排。', tones: ['formal', 'friendly', 'brief'], fields: [fields.recipient, fields.documentType, fields.handoverDate, fields.handoverMethod, fields.contact], optional_phrases: ['keep_safe', 'reply_confirm'] },
    { id: 'missing_documents', name: '文件補交通知', purpose: '提醒缺少文件、補交期限與提交方式。', tones: ['formal', 'friendly', 'brief'], fields: [fields.recipient, fields.missingDocuments, fields.submitDeadline, fields.submitMethod, fields.contact], optional_phrases: ['clear_photo', 'reply_confirm'] },
    { id: 'pickup', name: '接送或接機通知', purpose: '通知接送日期、時間、班機或車次、集合地點與聯絡方式。', tones: ['formal', 'friendly', 'brief'], fields: [fields.recipient, fields.pickupDate, fields.pickupTime, fields.flight, fields.pickupPlace, fields.pickupPerson, fields.contactMethod], optional_phrases: ['keep_phone_on', 'be_on_time', 'reply_confirm'] }
  ];
  function entry(scenario_id, language, tone, template, required_fields, optional_phrases) { return { scenario_id, language, tone, required_fields, optional_phrases, template, review_status: language === 'zh' ? 'reviewed' : 'needs-native-review' }; }
  function pack(scenario, required, optional, zh, id, vi, th) {
    const out = { zh: {}, id: {}, vi: {}, th: {} };
    Object.entries(zh).forEach(([tone, template]) => out.zh[tone] = entry(scenario, 'zh', tone, template, required, optional));
    Object.entries(id).forEach(([tone, template]) => out.id[tone] = entry(scenario, 'id', tone, template, required, optional));
    Object.entries(vi).forEach(([tone, template]) => out.vi[tone] = entry(scenario, 'vi', tone, template, required, optional));
    Object.entries(th).forEach(([tone, template]) => out.th[tone] = entry(scenario, 'th', tone, template, required, optional));
    return out;
  }
  const data = {
    onboarding: pack('onboarding', ['recipient_greeting', 'onboard_date', 'onboard_time', 'onboard_place', 'documents', 'contact_person_name'], ['arrive_early', 'bring_original', 'reply_confirm'],
      { formal: '{recipient_greeting}請於{onboard_date}{onboard_time}到{onboard_place}報到，並攜帶{documents}。聯絡人：{contact_person_name}。', friendly: '{recipient_greeting}提醒您報到時間是{onboard_date}{onboard_time}，地點在{onboard_place}，請記得攜帶{documents}。有問題可聯絡{contact_person_name}。', brief: '{recipient_greeting}報到：{onboard_date}{onboard_time}，地點：{onboard_place}，攜帶：{documents}。聯絡人：{contact_person_name}。' },
      { formal: '{recipient_greeting}mohon datang pada {onboard_date} pukul {onboard_time} di {onboard_place}. Mohon membawa {documents}. Narahubung: {contact_person_name}.', friendly: '{recipient_greeting}jadwal kedatangan Anda adalah {onboard_date} pukul {onboard_time} di {onboard_place}. Mohon membawa {documents}. Jika ada pertanyaan, hubungi {contact_person_name}.', brief: '{recipient_greeting}Kedatangan: {onboard_date} {onboard_time}. Lokasi: {onboard_place}. Bawa: {documents}. Kontak: {contact_person_name}.' },
      { formal: '{recipient_greeting}vui lòng đến nhận việc vào {onboard_date} lúc {onboard_time} tại {onboard_place}. Vui lòng mang theo {documents}. Người liên hệ: {contact_person_name}.', friendly: '{recipient_greeting}thời gian nhận việc là {onboard_date} lúc {onboard_time}, địa điểm tại {onboard_place}. Vui lòng mang theo {documents}. Nếu có câu hỏi, liên hệ {contact_person_name}.', brief: '{recipient_greeting}Nhận việc: {onboard_date} {onboard_time}. Địa điểm: {onboard_place}. Mang theo: {documents}. Liên hệ: {contact_person_name}.' },
      { formal: '{recipient_greeting}กรุณามารายงานตัววันที่ {onboard_date} เวลา {onboard_time} น. ที่ {onboard_place} กรุณานำ {documents} มาด้วย ผู้ติดต่อ: {contact_person_name}', friendly: '{recipient_greeting}กำหนดรายงานตัวคือวันที่ {onboard_date} เวลา {onboard_time} น. ที่ {onboard_place} กรุณานำ {documents} มาด้วย หากมีคำถาม โปรดติดต่อ {contact_person_name}', brief: '{recipient_greeting}รายงานตัว: {onboard_date} เวลา {onboard_time} น. สถานที่: {onboard_place} เอกสาร: {documents} ติดต่อ: {contact_person_name}' }),
    interview: pack('interview', ['recipient_greeting', 'interview_date', 'interview_time', 'interview_place', 'interview_method', 'documents', 'contact_person_name'], ['arrive_early', 'reply_confirm'],
      { formal: '{recipient_greeting}面試安排於{interview_date}{interview_time}，地點為{interview_place}，方式為{interview_method}。請攜帶{documents}。聯絡人：{contact_person_name}。', friendly: '{recipient_greeting}提醒您面試時間是{interview_date}{interview_time}，方式為{interview_method}，地點在{interview_place}。請攜帶{documents}，有問題可聯絡{contact_person_name}。', brief: '{recipient_greeting}面試：{interview_date}{interview_time}，方式：{interview_method}，地點：{interview_place}，攜帶：{documents}。聯絡人：{contact_person_name}。' },
      { formal: '{recipient_greeting}jadwal wawancara Anda adalah {interview_date} pukul {interview_time}. Lokasi: {interview_place}. Metode: {interview_method}. Mohon membawa {documents}. Narahubung: {contact_person_name}.', friendly: '{recipient_greeting}wawancara Anda pada {interview_date} pukul {interview_time}. Metode {interview_method} di {interview_place}. Mohon membawa {documents}. Hubungi {contact_person_name} jika ada pertanyaan.', brief: '{recipient_greeting}Wawancara: {interview_date} {interview_time}. Metode: {interview_method}. Lokasi: {interview_place}. Bawa: {documents}. Kontak: {contact_person_name}.' },
      { formal: '{recipient_greeting}lịch phỏng vấn là {interview_date} lúc {interview_time}. Địa điểm: {interview_place}. Hình thức: {interview_method}. Vui lòng mang theo {documents}. Người liên hệ: {contact_person_name}.', friendly: '{recipient_greeting}lịch phỏng vấn của bạn vào {interview_date} lúc {interview_time}. Hình thức {interview_method}, địa điểm {interview_place}. Vui lòng mang theo {documents}. Liên hệ {contact_person_name} nếu có câu hỏi.', brief: '{recipient_greeting}Phỏng vấn: {interview_date} {interview_time}. Hình thức: {interview_method}. Địa điểm: {interview_place}. Mang theo: {documents}. Liên hệ: {contact_person_name}.' },
      { formal: '{recipient_greeting}กำหนดสัมภาษณ์คือวันที่ {interview_date} เวลา {interview_time} น. สถานที่: {interview_place} วิธีการ: {interview_method} กรุณานำ {documents} มาด้วย ผู้ติดต่อ: {contact_person_name}', friendly: '{recipient_greeting}การสัมภาษณ์ของคุณคือวันที่ {interview_date} เวลา {interview_time} น. วิธีการ {interview_method} ที่ {interview_place} กรุณานำ {documents} มาด้วย ติดต่อ {contact_person_name} หากมีคำถาม', brief: '{recipient_greeting}สัมภาษณ์: {interview_date} เวลา {interview_time} น. วิธีการ: {interview_method} สถานที่: {interview_place} เอกสาร: {documents} ติดต่อ: {contact_person_name}' }),
    medical: pack('medical', ['recipient_greeting', 'medical_date', 'meet_time', 'meet_place', 'medical_place'], ['no_breakfast', 'bring_health_card', 'be_on_time', 'tell_medicine'],
      { formal: '{recipient_greeting}請於{medical_date}{meet_time}到{meet_place}集合，並前往{medical_place}體檢。', friendly: '{recipient_greeting}提醒您體檢日期是{medical_date}，請於{meet_time}到{meet_place}集合，體檢地點為{medical_place}。' },
      { formal: '{recipient_greeting}mohon berkumpul pada {medical_date} pukul {meet_time} di {meet_place} untuk pemeriksaan kesehatan di {medical_place}.', friendly: '{recipient_greeting}pemeriksaan kesehatan dijadwalkan pada {medical_date}. Mohon berkumpul pukul {meet_time} di {meet_place}. Lokasi pemeriksaan: {medical_place}.' },
      { formal: '{recipient_greeting}vui lòng tập trung vào {medical_date} lúc {meet_time} tại {meet_place} để đi khám sức khỏe tại {medical_place}.', friendly: '{recipient_greeting}lịch khám sức khỏe vào {medical_date}. Vui lòng tập trung lúc {meet_time} tại {meet_place}. Địa điểm khám: {medical_place}.' },
      { formal: '{recipient_greeting}กรุณามารวมตัววันที่ {medical_date} เวลา {meet_time} น. ที่ {meet_place} เพื่อไปตรวจสุขภาพที่ {medical_place}', friendly: '{recipient_greeting}กำหนดตรวจสุขภาพคือวันที่ {medical_date} กรุณามารวมตัวเวลา {meet_time} น. ที่ {meet_place} สถานที่ตรวจ: {medical_place}' }),
    passport_arc: pack('passport_arc', ['recipient_greeting', 'document_type', 'handover_date', 'handover_method', 'contact_person_name'], ['keep_safe', 'reply_confirm'],
      { formal: '{recipient_greeting}請於{handover_date}透過{handover_method}交付{document_type}。聯絡人：{contact_person_name}。', friendly: '{recipient_greeting}提醒您請在{handover_date}透過{handover_method}交付{document_type}。如有問題可聯絡{contact_person_name}。', brief: '{recipient_greeting}交付{document_type}：{handover_date}，方式：{handover_method}。聯絡人：{contact_person_name}。' },
      { formal: '{recipient_greeting}mohon menyerahkan {document_type} pada {handover_date} melalui {handover_method}. Narahubung: {contact_person_name}.', friendly: '{recipient_greeting}mohon menyerahkan {document_type} pada {handover_date} dengan cara {handover_method}. Jika ada pertanyaan, hubungi {contact_person_name}.', brief: '{recipient_greeting}Serahkan {document_type} pada {handover_date}. Cara: {handover_method}. Kontak: {contact_person_name}.' },
      { formal: '{recipient_greeting}vui lòng giao {document_type} vào {handover_date} theo cách {handover_method}. Người liên hệ: {contact_person_name}.', friendly: '{recipient_greeting}vui lòng giao {document_type} vào {handover_date} bằng cách {handover_method}. Nếu có câu hỏi, liên hệ {contact_person_name}.', brief: '{recipient_greeting}Giao {document_type} vào {handover_date}. Cách giao: {handover_method}. Liên hệ: {contact_person_name}.' },
      { formal: '{recipient_greeting}กรุณาส่งมอบ {document_type} วันที่ {handover_date} โดยวิธี {handover_method} ผู้ติดต่อ: {contact_person_name}', friendly: '{recipient_greeting}กรุณาส่งมอบ {document_type} วันที่ {handover_date} โดยวิธี {handover_method} หากมีคำถาม โปรดติดต่อ {contact_person_name}', brief: '{recipient_greeting}ส่งมอบ {document_type}: {handover_date} วิธี: {handover_method} ติดต่อ: {contact_person_name}' }),
    missing_documents: pack('missing_documents', ['recipient_greeting', 'missing_documents', 'submit_deadline', 'submit_method', 'contact_person_name'], ['clear_photo', 'reply_confirm'],
      { formal: '{recipient_greeting}目前尚缺{missing_documents}，請於{submit_deadline}前透過{submit_method}補交。聯絡人：{contact_person_name}。', friendly: '{recipient_greeting}提醒您還需要補交{missing_documents}，請在{submit_deadline}前用{submit_method}提交。有問題可聯絡{contact_person_name}。', brief: '{recipient_greeting}缺少文件：{missing_documents}。期限：{submit_deadline}。方式：{submit_method}。聯絡人：{contact_person_name}。' },
      { formal: '{recipient_greeting}dokumen yang masih kurang adalah {missing_documents}. Mohon melengkapi sebelum {submit_deadline} melalui {submit_method}. Narahubung: {contact_person_name}.', friendly: '{recipient_greeting}dokumen {missing_documents} masih perlu dilengkapi. Mohon kirim sebelum {submit_deadline} melalui {submit_method}. Hubungi {contact_person_name} jika ada pertanyaan.', brief: '{recipient_greeting}Dokumen kurang: {missing_documents}. Batas waktu: {submit_deadline}. Cara kirim: {submit_method}. Kontak: {contact_person_name}.' },
      { formal: '{recipient_greeting}giấy tờ còn thiếu là {missing_documents}. Vui lòng bổ sung trước {submit_deadline} bằng cách {submit_method}. Người liên hệ: {contact_person_name}.', friendly: '{recipient_greeting}bạn cần bổ sung {missing_documents}. Vui lòng nộp trước {submit_deadline} qua {submit_method}. Liên hệ {contact_person_name} nếu có câu hỏi.', brief: '{recipient_greeting}Giấy tờ thiếu: {missing_documents}. Hạn: {submit_deadline}. Cách nộp: {submit_method}. Liên hệ: {contact_person_name}.' },
      { formal: '{recipient_greeting}เอกสารที่ยังขาดคือ {missing_documents} กรุณาส่งเพิ่มเติมก่อนวันที่ {submit_deadline} โดยวิธี {submit_method} ผู้ติดต่อ: {contact_person_name}', friendly: '{recipient_greeting}คุณยังต้องส่ง {missing_documents} เพิ่มเติม กรุณาส่งก่อนวันที่ {submit_deadline} ผ่าน {submit_method} หากมีคำถาม โปรดติดต่อ {contact_person_name}', brief: '{recipient_greeting}เอกสารขาด: {missing_documents} กำหนดส่ง: {submit_deadline} วิธีส่ง: {submit_method} ติดต่อ: {contact_person_name}' }),
    pickup: pack('pickup', ['recipient_greeting', 'pickup_date', 'pickup_time', 'flight_or_trip', 'pickup_place', 'pickup_person_name', 'contact_method'], ['keep_phone_on', 'be_on_time', 'reply_confirm'],
      { formal: '{recipient_greeting}接送安排於{pickup_date}{pickup_time}，班機或車次：{flight_or_trip}。集合地點為{pickup_place}，接送人：{pickup_person_name}，聯絡方式：{contact_method}。', friendly: '{recipient_greeting}提醒您接送時間是{pickup_date}{pickup_time}，班機或車次：{flight_or_trip}。請到{pickup_place}集合，接送人是{pickup_person_name}，聯絡方式：{contact_method}。', brief: '{recipient_greeting}接送：{pickup_date}{pickup_time}。班機／車次：{flight_or_trip}。集合：{pickup_place}。接送人：{pickup_person_name}。聯絡：{contact_method}。' },
      { formal: '{recipient_greeting}jadwal penjemputan adalah {pickup_date} pukul {pickup_time}. Nomor penerbangan atau perjalanan: {flight_or_trip}. Titik kumpul: {pickup_place}. Penjemput: {pickup_person_name}. Kontak: {contact_method}.', friendly: '{recipient_greeting}jadwal penjemputan pada {pickup_date} pukul {pickup_time}. Nomor penerbangan atau perjalanan: {flight_or_trip}. Mohon berkumpul di {pickup_place}. Penjemput: {pickup_person_name}. Kontak: {contact_method}.', brief: '{recipient_greeting}Jemput: {pickup_date} {pickup_time}. Penerbangan/perjalanan: {flight_or_trip}. Titik kumpul: {pickup_place}. Penjemput: {pickup_person_name}. Kontak: {contact_method}.' },
      { formal: '{recipient_greeting}lịch đón là {pickup_date} lúc {pickup_time}. Số chuyến bay hoặc chuyến xe: {flight_or_trip}. Điểm tập trung: {pickup_place}. Người đón: {pickup_person_name}. Liên hệ: {contact_method}.', friendly: '{recipient_greeting}lịch đón vào {pickup_date} lúc {pickup_time}. Số chuyến bay hoặc chuyến xe: {flight_or_trip}. Vui lòng tập trung tại {pickup_place}. Người đón: {pickup_person_name}. Liên hệ: {contact_method}.', brief: '{recipient_greeting}Đón: {pickup_date} {pickup_time}. Chuyến bay/xe: {flight_or_trip}. Điểm tập trung: {pickup_place}. Người đón: {pickup_person_name}. Liên hệ: {contact_method}.' },
      { formal: '{recipient_greeting}กำหนดรับคือวันที่ {pickup_date} เวลา {pickup_time} น. เที่ยวบินหรือเที่ยวรถ: {flight_or_trip} จุดนัดพบ: {pickup_place} ผู้รับ: {pickup_person_name} ติดต่อ: {contact_method}', friendly: '{recipient_greeting}กำหนดรับคือวันที่ {pickup_date} เวลา {pickup_time} น. เที่ยวบินหรือเที่ยวรถ: {flight_or_trip} กรุณารวมตัวที่ {pickup_place} ผู้รับคือ {pickup_person_name} ติดต่อได้ที่ {contact_method}', brief: '{recipient_greeting}รับ: {pickup_date} เวลา {pickup_time} น. เที่ยวบิน/รถ: {flight_or_trip} จุดนัดพบ: {pickup_place} ผู้รับ: {pickup_person_name} ติดต่อ: {contact_method}' })
  };
  window.ForeignWorkforceMessageTemplates = { languages, tones, fieldLabels, scenarios, data };
})();
